name: zkLLVM Tag Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create releases for'
        required: true
        type: string

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
    runs-on: ${{matrix.host}}
    container:
      image: ${{matrix.container}}
      credentials:
        username: ${{github.actor}}
        password: ${{secrets.GNUS_TOKEN_1}}
    strategy:
      fail-fast: false
      matrix:
        target: [Android, iOS, OSX, Linux, Windows]
        build-type: [Debug,Release]
        abi: [""]
        include:
          - target: Android
            host: ubuntu-22.04
            abi: arm64-v8a
            build-type: Release
          - target: Android
            host: ubuntu-22.04
            abi: armeabi-v7a
            build-type: Release
          - target: iOS
            host: macos-latest
          - target: OSX
            host: gv-OSX-Large
          - target: Linux
            host: ubuntu-22.04
            abi: x86_64
            build-type: Release
          - target: Linux
            host: ubuntu-24.04-arm
            abi: aarch64
            build-type: Release
            container: ghcr.io/geniusventures/debian-bullseye:latest
          - target: Windows
            host: windows-latest
        exclude:
          - target: Android
            abi: ""
          - target: Linux
            abi: ""
          - target: OSX
            build-type: Debug
          - target: iOS
            build-type: Debug
    steps:
      - name: Configure Linux host
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
          sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
          sudo update-alternatives --set cc $(which clang)
          sudo update-alternatives --set c++ $(which clang++)

          sudo apt install ccache ninja-build -y
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Configure Windows host
        if: ${{ runner.os == 'Windows'}}
        run: |
          choco install ccache -y

      - name: Configure macOS host
        if: ${{ runner.os == 'macOS'}}
        run: |
          brew install ccache ninja bash gnu-tar
          # Ensure GNU tar is first in PATH - check both possible Homebrew locations
          if [ -d "/opt/homebrew/opt/gnu-tar/libexec/gnubin" ]; then
            echo "PATH=/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV
            echo "Using GNU tar from /opt/homebrew"
          elif [ -d "/usr/local/opt/gnu-tar/libexec/gnubin" ]; then
            echo "PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH" >> $GITHUB_ENV
            echo "Using GNU tar from /usr/local"
          else
            echo "WARNING: GNU tar installation not found in expected locations"
            echo "Available tar: $(which tar)"
          fi
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Add Android toolchain
        if: ${{ matrix.target == 'Android' }}
        run: |
          NDK_VERSION="r27b"
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME

          echo "ANDROID_NDK_HOME=$HOME/android-ndk-$NDK_VERSION" >> $GITHUB_ENV

      - name: Clean workspace (self-hosted runners)
        if: ${{ runner.environment == 'self-hosted' }}
        working-directory: ${{github.workspace}}
        run: |
          echo "=== PRE-CLEANUP DEBUG ==="
          echo "Current working directory: $(pwd)"
          echo "Contents of workspace:"
          ls -la
          echo "Checking for zkLLVM directory..."
          if [ -d "zkLLVM" ]; then
            echo "zkLLVM directory exists, contents:"
            ls -la zkLLVM/
            if [ -d "zkLLVM/build" ]; then
              echo "Build directory exists, checking for build artifacts:"
              if [ -d "zkLLVM/build/OSX/Release" ]; then
                echo "Found existing Release build artifacts:"
                ls -la zkLLVM/build/OSX/Release/
              else
                echo "No Release build artifacts found"
              fi
            fi
          else
            echo "zkLLVM directory does not exist"
          fi
          
          echo "=== CLEANUP ==="
          # Clean up artifacts from previous runs (self-hosted runners only)
          if [ -d "thirdparty" ]; then
            echo "Removing thirdparty directory..."
            rm -rf thirdparty
          fi
          # Clean up any existing zkLLVM directory from previous checkout
          if [ -d "zkLLVM" ]; then
            echo "Removing zkLLVM directory..."
            rm -rf zkLLVM
          fi
          
          echo "=== POST-CLEANUP DEBUG ==="
          echo "Contents after cleanup:"
          ls -la
        shell: bash

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zkLLVM
          submodules: "recursive"
          ref: ${{ github.event.inputs.tag }}

      - name: Set build directory
        run: |
          if [ '${{matrix.abi}}' ]; then
            BUILD_DIRECTORY=${{matrix.build-type}}/${{matrix.abi}}
          else
            BUILD_DIRECTORY=${{matrix.build-type}}
          fi

          echo "SOURCE_DIRECTORY=build/${{matrix.target}}" >> $GITHUB_ENV
          echo "BUILD_DIRECTORY=$BUILD_DIRECTORY" >> $GITHUB_ENV
        shell: bash

      - name: Download thirdparty release
        working-directory: ${{github.workspace}}
        run: |
          TAG_NAME="${{ github.event.inputs.tag }}"
          echo "Building for tag: ${TAG_NAME}"

          if [ '${{matrix.abi}}' ]; then
            FILE_NAME=${{matrix.target}}-${{matrix.abi}}-${{matrix.build-type}}.tar.gz
          else
            FILE_NAME=${{matrix.target}}-${{matrix.build-type}}.tar.gz
          fi
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

          mkdir thirdparty
          cd thirdparty
          pwd

          # Download from the tag's release
          echo "Downloading thirdparty from tag: ${TAG_NAME}"

          gh release download ${TAG_NAME} --repo GeniusVentures/thirdparty -p "${FILE_NAME}"
          tar -zxvf "${FILE_NAME}"

          # Set THIRDPARTY_BUILD_DIR to the actual location where files were extracted
          
          if [ "${{ matrix.target }}" = "Windows" ]; then
            # Convert Unix path to Windows path for Windows builds
            echo "THIRDPARTY_BUILD_DIR=$(pwd -W)/${{env.SOURCE_DIRECTORY}}/${{env.BUILD_DIRECTORY}}" >> $GITHUB_ENV
          else
            echo "THIRDPARTY_BUILD_DIR=$(pwd)/${{env.SOURCE_DIRECTORY}}/${{env.BUILD_DIRECTORY}}" >> $GITHUB_ENV
          fi

        shell: bash

      - name: Configure CMake for Android
        if: ${{ matrix.target == 'Android'}}
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_STANDARD=17 -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty/${{env.SOURCE_DIRECTORY}} -DTHIRDPARTY_BUILD_DIR=${{env.THIRDPARTY_BUILD_DIR}} -DANDROID_ABI=${{matrix.abi}} -DCMAKE_ANDROID_NDK=${ANDROID_NDK_HOME}

      - name: Configure CMake for iOS
        if: ${{ matrix.target == 'iOS'}}
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_STANDARD=17 -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty/${{env.SOURCE_DIRECTORY}} -DTHIRDPARTY_BUILD_DIR=${{env.THIRDPARTY_BUILD_DIR}} -DPLATFORM=OS64

      - name: Configure CMake for Mac
        if: ${{ matrix.target == 'OSX'}}
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_STANDARD=17 -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty/${{env.SOURCE_DIRECTORY}} -DTHIRDPARTY_BUILD_DIR=${{env.THIRDPARTY_BUILD_DIR}} -DPLATFORM=MAC_UNIVERSAL

      - name: Configure CMake for Linux
        if: ${{ matrix.target == 'Linux' }}
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_STANDARD=17 -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty/${{env.SOURCE_DIRECTORY}} -DTHIRDPARTY_BUILD_DIR=${{env.THIRDPARTY_BUILD_DIR}} -DABI_SUBFOLDER_NAME='/${{matrix.abi}}'

      - name: Configure CMake for Windows
        if: ${{ matrix.target == 'Windows' }}
        working-directory: ${{github.workspace}}\zkLLVM
        run: |
          cd ${{env.SOURCE_DIRECTORY}}
          cmake  -B ${{env.BUILD_DIRECTORY}} -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DCMAKE_C_STANDARD=17 -DTHIRDPARTY_DIR=${{github.workspace}}\thirdparty/${{env.SOURCE_DIRECTORY}} -DTHIRDPARTY_BUILD_DIR=${{env.THIRDPARTY_BUILD_DIR}}  -G "Visual Studio 17 2022" -A x64

      - name: Build
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake --build ${{env.BUILD_DIRECTORY}} --config ${{matrix.build-type}} -j

      - name: Install
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}
        run: cmake --install ${{env.BUILD_DIRECTORY}}

      - name: Create or check release
        working-directory: ${{github.workspace}}/zkLLVM
        shell: bash
        run: |
          TAG_NAME='${{ github.event.inputs.tag }}'
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

          echo "Checking if GitHub release exists for tag: $TAG_NAME"

          set +e
          gh release view $TAG_NAME
          releaseFound=$?
          set -e

          if [[ $releaseFound -ne 0 ]]; then
              echo "Release not found, creating for tag: $TAG_NAME"

              # Create a single release for the tag
              gh release create $TAG_NAME \
                  -n "Build artifacts for tag ${TAG_NAME}" \
                  -t "${TAG_NAME} build artifacts"
          else
              echo "Release already exists for tag: $TAG_NAME"
          fi

      - name: Compress build artifacts
        working-directory: ${{github.workspace}}/zkLLVM/${{env.SOURCE_DIRECTORY}}/${{env.BUILD_DIRECTORY}}
        shell: bash
        env:
          DESTINATION_DIRECTORY: ${{github.workspace}}/zkLLVM/${{env.FILE_NAME}}
        run: |
          tar -czvf ${FILE_NAME} \
              --exclude='zkLLVM/src' \
              --exclude='zkLLVM/tmp' \
              --transform 's|^|${{env.SOURCE_DIRECTORY}}/${{env.BUILD_DIRECTORY}}/|S' \
              zkLLVM

          mv ${FILE_NAME} "$DESTINATION_DIRECTORY"

      - name: Release file
        working-directory: ${{github.workspace}}/zkLLVM
        shell: bash
        run: |
          echo -e "Uploading ${FILE_NAME} to release ${TAG_NAME}"
          gh release upload --clobber ${TAG_NAME} ${FILE_NAME}