name: Release Build CI

# Controls when the workflow will run
# Triggers the workflow on push or pull request events and manually from the Actions tab
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GNUS_TOKEN_1 }}
    runs-on: ${{matrix.host}}
    strategy:
      fail-fast: false
      matrix:
        target: [Android, iOS, OSX, Linux, Windows]
        build-type: [Release]
        abi: [""]
        include:
          - target: Android
            host: ubuntu-22.04
            abi: arm64-v8a
            build-type: Release
          - target: Android
            host: ubuntu-22.04
            abi: armeabi-v7a
            build-type: Release
          - target: iOS
            host: macos-latest
          - target: OSX
            host: macos-latest
          - target: Linux
            host: ubuntu-22.04
          - target: Windows
            host: windows-latest
        exclude:
          - target: Android
            abi: ""
    steps:
      - name: Configure Linux host
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo update-alternatives --install /usr/bin/cc cc $(which clang) 100
          sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++) 100
          sudo update-alternatives --set cc $(which clang)
          sudo update-alternatives --set c++ $(which clang++)

          sudo apt install ccache ninja-build -y
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Configure Windows host
        if: ${{ runner.os == 'Windows'}}
        run: |
          choco install ccache -y

      - name: Configure macOS host
        if: ${{ runner.os == 'macOS'}}
        run: |
          brew install ccache ninja bash gnu-tar
          PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV

      - name: Add Android toolchain
        if: ${{ matrix.target == 'Android' }}
        run: |
          NDK_VERSION="r27b"
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME

          echo "ANDROID_NDK_HOME=$HOME/android-ndk-$NDK_VERSION" >> $GITHUB_ENV

      - name: Set build directory
        run: |
          if [ '${{matrix.abi}}' ]; then
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}/${{matrix.abi}}
          else
            BUILD_DIRECTORY=build/${{matrix.target}}/${{matrix.build-type}}
          fi
          echo "BUILD_DIRECTORY=$BUILD_DIRECTORY" >> $GITHUB_ENV
        shell: bash

      - name: Download Prebuilt Boost from Thirdparty
        shell: bash
        run: |
          if git ls-remote --heads https://github.com/GeniusVentures/thirdparty.git $current_branch | grep -q $current_branch; then
              thirdparty_branch=${current_branch}
          else
              thirdparty_branch=develop
          fi

          echo "Using ${thirdparty_branch} for thirdparty"

          if [ '${{matrix.abi}}' ]; then
            thirdparty_tag="${{matrix.target}}-${{matrix.abi}}-${thirdparty_branch}-${{matrix.build-type}}"
          else
            thirdparty_tag="${{matrix.target}}-${thirdparty_branch}-${{matrix.build-type}}"
          fi

          gh release download \
            --repo GeniusVentures/thirdparty \
            ${thirdparty_tag} \
            --pattern Boost-lib.tar.gz

          mkdir -p ${{github.workspace}}/thirdparty/${{env.BUILD_DIRECTORY}}

      - name: Extract Boost
        run: |
          mkdir -p thirdparty/${{env.BUILD_DIRECTORY}}
          tar -xzf Boost-lib.tar.gz -C thirdparty/${{env.BUILD_DIRECTORY}}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "zkLLVM"
          submodules: "recursive"

      - name: Configure CMake for Android
        if: ${{ matrix.target == 'Android'}}
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty -DANDROID_ABI=${{matrix.abi}} -DCMAKE_ANDROID_NDK=${ANDROID_NDK_HOME}

      - name: Configure CMake for iOS
        if: ${{ matrix.target == 'iOS'}}
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty -DPLATFORM=OS64

      - name: Configure CMake for Mac
        if: ${{ matrix.target == 'OSX'}}
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty -DPLATFORM=MAC_UNIVERSAL

      - name: Configure CMake for Linux
        if: ${{ matrix.target == 'Linux' }}
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake -S build/${{matrix.target}} -B $BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty

      - name: Configure CMake for Windows
        if: ${{ matrix.target == 'Windows' }}
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake -S build/${{matrix.target}} -B $env:BUILD_DIRECTORY -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -DTHIRDPARTY_DIR=${{github.workspace}}/thirdparty -G "Visual Studio 17 2022" -A x64

      - name: Build
        working-directory: ${{github.workspace}}/zkLLVM
        run: cmake --build ${{env.BUILD_DIRECTORY}} --config ${{matrix.build-type}} -j

      - name: Install
        working-directory: ${{github.workspace}}/zkLLVM/${{env.BUILD_DIRECTORY}}
        run: cmake --install .

      - name: Compressing build artifacts
        working-directory: ${{github.workspace}}/zkLLVM/${{env.BUILD_DIRECTORY}}
        if: ${{github.event_name == 'workflow_dispatch'}}
        shell: bash
        run: |
          tar --exclude="build/${{matrix.target}}/${{matrix.build-type}}/armeabi-v7a/zkLLVM/src" \
              --exclude="build/${{matrix.target}}/${{matrix.build-type}}/armeabi-v7a/zkLLVM/tmp" \
              --exclude="build/${{matrix.target}}/${{matrix.build-type}}/arm64-v8a/zkLLVM/src" \
              --exclude="build/${{matrix.target}}/${{matrix.build-type}}/arm64-v8a/zkLLVM/tmp" \
              --exclude="build/${{matrix.target}}/${{matrix.build-type}}/zkLLVM/src" \
              --exclude="build/${{matrix.target}}/${{matrix.build-type}}/zkLLVM/tmp" \
              -czvf zkLLVM.tar.gz \
              --transform "s|^|${{env.BUILD_DIRECTORY}}/|" \
              -C ${{github.workspace}}/zkLLVM ${{env.BUILD_DIRECTORY}}

      - name: Move Archive (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: Move-Item -Path "zkLLVM.tar.gz" -Destination "$env:GITHUB_WORKSPACE\zkLLVM.tar.gz"
    
      - name: Move Archive (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: mv zkLLVM.tar.gz "${{ github.workspace }}/zkLLVM.tar.gz"

      - name: Release file
        shell: bash
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ '${{matrix.abi}}' ]; then
            OS_NAME=${{matrix.target}}-${{matrix.abi}}
          else
            OS_NAME=${{matrix.target}}
          fi

          if ${{github.event_name == 'pull_request'}}; then
              branch_name=${{ github.event.pull_request.head.ref }}
          else
              branch_name=$GITHUB_REF_NAME
          fi

          file_name="${OS_NAME}-${branch_name}-${{matrix.build-type}}.tar.gz"
          RELEASE_TAG=${OS_NAME}-${branch_name}-${{matrix.build-type}}

          mv zkLLVM.tar.gz ${file_name}

          if ! gh release view $RELEASE_TAG --repo GeniusVentures/zkLLVM; then
              echo "Release not found, creating tag ${RELEASE_TAG}"

              if [ '${{matrix.build-type}}' != 'Release' ]; then
                  RELEASE_TYPE="--prerelease"
              else
                  RELEASE_TYPE="--latest"
              fi

              gh release create ${RELEASE_TAG} \
                  -n "${CURRENT_BRANCH} branch"  \
                  --target "${CURRENT_BRANCH}" \
                  ${RELEASE_TYPE} \
                  --repo GeniusVentures/zkLLVM \
                  -t "${{matrix.target}} ${{matrix.abi && format('({0}) ', matrix.abi) || ''}}${CURRENT_BRANCH} branch ${{matrix.build-type}} build"
          fi
          
          echo "Uploading ${file_name}"
          gh release upload ${RELEASE_TAG} ${file_name} --repo GeniusVentures/zkLLVM --clobber
